CREATE ROLE vinicius SUPERUSER;
CREATE ROLE vinicius CREATEDB;
CREATE ROLE vinicius CREATEROLE;
CREATE ROLE vinicius REPLICATION LOGIN;
CREATE ROLE vinicius PASSWORD 'string';
CREATE ROLE vinicius PASSWORD '123456' CREATEDB;
