version: '3.8'

services:

  ghost:
    image: ghost:5-alpine
    ports:
      - 8080:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: DVSAdsadvEwqewEwQWE#
      database__connection__database: ghost
    volumes:
      - ghost:/var/lib/ghost/content
    networks:
      - public
      - private
    depends_on:
      - db
    deploy:
      replicas: 1

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: DVSAdsadvEwqewEwQWE#
    volumes:
      - db:/var/lib/mysql
    networks:
      - private

volumes:
  ghost:
  db:

networks:
  public:
  private: