spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alura
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update
      format_sql: true
      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
